### ISSUE TITLE
Blocky Python

### ISSUE THREAD

**Issue by runtimevic** [andrewjensen/light-blocks#4]
Hello @andrewjensen 
I like your project, congratulations. 
 My question is, do you know if blocky can be integrated into Python?
Or where can I look for this information? 
 thank you.

**Comment by runtimevic** [comment]
Hi @andrewjensen ,
do you know if blockly, in addition to being in javascript with react or node.js, can be integrated with another language python, go, rust, etc. to add your own blocks?
Thanks

**Comment by andrewjensen** [comment]
Hi @runtimevic, great questions!

You can think of Blockly as two things:

- The UI: the visual programming blocks that a user can move around
  - This needs to be in JavaScript/TypeScript. It doesn't necessarily need to be built in the React framework - I'd guess there are some great libraries in other frameworks that make integration easy as well.
- The interpreter: the logic that reads the raw XML data from the blocks and then executes it as code
  - This part is much more freeform. You could generate and interpret code in the browser (see [this doc](https://developers.google.com/blockly/guides/create-custom-blocks/code-generation/overview)), or you could send the XML data to a backend server (in Python, for example) and then have the server actually execute the code. This is option that light-blocks follows.

I'd recommend going through these resources to learn more:

- [Blockly homepage](https://developers.google.com/blockly/guides/get-started/what-is-blockly): Includes a great overview of how the project works
- [Blockly developer docs](https://developers.google.com/blockly/guides/get-started/what-is-blockly): Includes in-depth information about how to embed Blockly into an app
- [Blockly developer tools](https://developers.google.com/blockly/guides/create-custom-blocks/blockly-developer-tools): Includes an interactive (blockly-based!) environment to design custom blocks to use in your app

I hope you create something awesome with Blockly!
