### ISSUE TITLE
Server error

### ISSUE THREAD

**Issue by runtimevic** [andrewjensen/light-blocks#7]
Hello @andrewjensen 
I have this error and I don't know how to fix it, can you think of anything I can do?
<img width="809" alt="LightBlocks_Server_Error1" src="https://github.com/andrewjensen/light-blocks/assets/53791834/0df800a6-9c4d-429f-9791-27a554f840ec">

**Comment by andrewjensen** [comment]
Hi @runtimevic, I'm guessing that your `$HUE_BRIDGE_IP_ADDRESS` environment variable is set incorrectly. It should be in the format of an IP address on your network, like this:

```
192.168.0.123
```

**Comment by runtimevic** [comment]
Hello, problerm is fix, closed issues
